### ISSUE TITLE
Not deployable due to validator dependencies / CDI

### ISSUE THREAD

**Issue by djmj** [konik-io/konik#60]
Hello, i succesfully created a Zugferd compliant invoice with this library in a console app but could not deploy it to a glassfish 5 server.

The validator classes _ValidatorInvoice_ and _MonetarySummationValidator_ have direct dependencies on
apache validation and google commons guava. Glassfish already comes with hibernate validator.

Furthermore _ValidatorInvoice_ uses CDI annotations _@Singleton_ and injections which lead to following exception:

	2018-09-24T23:29:04.818+0000|Information: WELD-000119: Not generating any bean definitions from io.konik.PdfHandler because of underlying class loading error: Type io.konik.harness.AppendParameter not found.  If this is unexpected, enable DEBUG logging to see the full error.
	2018-09-24T23:29:06.208+0000|Schwerwiegend: Exception during lifecycle processing
	org.glassfish.deployment.common.DeploymentException: CDI deployment failure:WELD-001408: Unsatisfied dependencies for type MonetarySummationValidator with qualifiers @Default
	  at injection point [BackedAnnotatedParameter] Parameter 2 of [BackedAnnotatedConstructor] @Inject public io.konik.validation.InvoiceValidator(Validator, MonetarySummationValidator)
	  at io.konik.validation.InvoiceValidator.<init>(InvoiceValidator.java:56)
		at org.glassfish.weld.WeldDeployer.event(WeldDeployer.java:239)

 **@Singleton**

The singleton pattern seems a little to forcing. Should this not be within the responsibility and scope of the implementing application? 

We use _hibernate ORM / validator_ and already have a singleton bean _Validator_ in our application and validate _Invoice_ like any other bean:

	this.validator.validate(invoice, InvoiceValidator.resolveIntoValidationGroups(level));

The drawback is the lost _MonetarySummation_ validation which relates to #61.

**Comment by Vad1mo** [comment]
@djmj did you check the Setup section in the docs?

https://konik.io/docs/index.html#setup 

This deals with Java EE. However if it isn't working it might need and update to comply with usecase for EE7/8
